apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 8
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - name: con
          image: quay.io/rehman0288/production:v3

      tolerations:
        - key: size
          operator: Equal
          value: large
          effect: NoSchedule

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: disk
                  operator: In             # NotIn, Exists, DoesNotExists
                  values: 
                    - ssd
                    - hdd
