apiVersion: v1
kind: LimitRange
metadata:
  name: container-limit
  namespace: dev
spec:
  limits:
    - min:
        cpu: 50m
        memory: 100Mi
      max:
        cpu: 800m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 200Mi
      default:
        cpu: 500m
        memory: 500Mi
      type: Container
