apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  containers:
  - name: con1
    image: quay.io/rehman0288/webapp
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c","while true;do echo hello;sleep 1;done"] 
