apiVersion: v1
kind: Pod
metadata:
  name: pod11
  namespace: dev
spec:
  containers:
  - name: con1
    image: quay.io/rehman0288/webapp
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: 150Mi
        cpu: 100m
