apiVersion: v1
kind: Pod
metadata:
  name: pod6
  labels:
    env: dev
    tier: frontend
spec:
  containers:
  - name: con1
    image: quay.io/rehman0288/webapp
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
