apiVersion: v1
kind: Pod
metadata:
  name: pod17
spec:
  containers:
  - name: con1
    image: quay.io/rehman0288/webapp
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /mydata
        name: vol1

  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: pvc01
