apiVersion: v1
kind: Pod
metadata:
  name: pod10
spec:
  containers:
  - name: con1
    image: quay.io/rehman0288/webapp
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 100Mi
        cpu: 100m
