apiVersion: v1
kind: Service
metadata:
  name: external
  labels:
    type: frontend
spec:
  type: NodePort
  selector:
    app: deploy
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
