apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sec-rolebinding
  namespace: hclns
subjects:
  - kind: User
    name: k8sec
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: k8sec-role
  apiGroup: rbac.authorization.k8s.io
