apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8sec-role
  namespace: hclns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","create"]
  - apiGroups: ["extensions","apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","delete"]
