apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-app
  namespace: cafe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
        - name: con
          image: quay.io/rehman0288/tea
          ports:
          - containerPort: 80
