apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: cafe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: con
          image: quay.io/rehman0288/webapp
          ports:
          - containerPort: 80
